# Generated by Django 3.2 on 2024-02-18 12:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_aboutpageseo_aboutpageseotranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpageseo',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube Link'),
        ),
        migrations.AddField(
            model_name='aboutpageseotranslation',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='aboutpageseotranslation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutpageseotranslation',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
    ]
