# Generated by Django 3.2 on 2024-02-18 17:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_aboutdoctorpageseo_aboutdoctorpageseotranslation_jineartclinicpageseo_jineartclinicpageseotranslatio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Banner Image')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='how_it_works/', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='how_it_works/', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='how_it_works/', verbose_name='Image 3')),
                ('meta_keywords', models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'How It Works Page SEO',
                'verbose_name_plural': 'How It Works Page SEO',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HowItWorksPageSeoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması')),
                ('banner_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner Title')),
                ('banner_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Banner Description')),
                ('subtitle1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle 1')),
                ('title1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title 1')),
                ('content1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content 1')),
                ('subtitle2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle 2')),
                ('title2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title 2')),
                ('content2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content 2')),
                ('subtitle3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle 3')),
                ('title3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title 3')),
                ('content3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content 3')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.howitworkspageseo')),
            ],
            options={
                'verbose_name': 'How It Works Page SEO Translation',
                'db_table': 'page_howitworkspageseo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
