# Generated by Django 3.2 on 2024-02-19 16:21

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_experienceitem_experiencepageseo_experiencepageseotranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Experience Category',
                'verbose_name_plural': 'Experience Categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='is_clinic',
            field=models.BooleanField(default=False, verbose_name='In Jineart Clinic?'),
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='is_lab',
            field=models.BooleanField(default=False, verbose_name='In Jineart Lab?'),
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.experiencecategory', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='ExperienceCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.experiencecategory')),
            ],
            options={
                'verbose_name': 'Experience Category Translation',
                'db_table': 'page_experiencecategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
