# Generated by Django 3.2 on 2024-02-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_privacypageseo_privacypageseotranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='in_home',
            field=models.BooleanField(default=False, verbose_name='In Home Page?'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='in_navbar',
            field=models.BooleanField(default=False, verbose_name='In Navigation?'),
        ),
    ]
