# Generated by Django 3.2 on 2024-02-20 11:19

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_auto_20240220_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('order', models.IntegerField(default=0, verbose_name='Ordering')),
                ('image', models.ImageField(blank=True, null=True, upload_to='patient-comments/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Patient Comment',
                'verbose_name_plural': 'Patient Comments',
                'ordering': ('order',),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PatientCommentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('role', models.CharField(blank=True, max_length=200, null=True, verbose_name='Role')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.patientcomment')),
            ],
            options={
                'verbose_name': 'Patient Comment Translation',
                'db_table': 'page_patientcomment_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
