# Generated by Django 3.2 on 2024-02-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_pricingplan_pricingplanfeature_pricingplanfeaturetranslation_pricingplantranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/authors', verbose_name='Author Image'),
        ),
    ]
