# Generated by Django 3.2 on 2024-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20240220_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdoctorpageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='aboutpageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='blog',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='blogspageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='contactpageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='experiencepageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='gdprpageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='howitworkspageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='jineartclinicpageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='jineartlabpageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='journeypageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='privacypageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='servicespageseo',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
    ]
