# Generated by Django 3.2 on 2024-05-31 08:49

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20240522_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='keywordstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Keyword Translation'},
        ),
        migrations.AlterField(
            model_name='aboutdoctorpageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='aboutdoctorpageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='aboutdoctorpageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='aboutpageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='aboutpageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='aboutpageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='blogspageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='blogspageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='blogspageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='blogtranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='blogtranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='contactpageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='contactpageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='contactpageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='experiencepageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='experiencepageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='experiencepageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='gdprpageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='gdprpageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='gdprpageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='homepageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='homepageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='homepageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='howitworkspageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='howitworkspageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='howitworkspageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='jineartclinicpageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='jineartclinicpageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='jineartclinicpageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='jineartlabpageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='jineartlabpageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='jineartlabpageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='journeypageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='journeypageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='journeypageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='keywordstranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='privacypageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='privacypageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='privacypageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='serviceitemtranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='serviceitemtranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='servicespageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='servicespageseotranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='servicespageseotranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.aboutpageseo', verbose_name='About Page')),
                ('about_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.jineartclinicpageseo', verbose_name='Jineart Clinic Page')),
                ('about_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.aboutdoctorpageseo', verbose_name='Cengiz Sagiroglu Page')),
                ('about_lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.jineartlabpageseo', verbose_name='Jineart Lab Page')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.blog', verbose_name='Blog')),
                ('howitworks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.howitworkspageseo', verbose_name='How It Works Page')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.serviceitem', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Frequently Asked Question',
                'verbose_name_plural': 'Frequently Asked Questions',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=250, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.faq')),
            ],
            options={
                'verbose_name': 'Frequently Asked Question Translation',
                'db_table': 'page_faq_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
