# Generated by Django 3.2 on 2024-05-31 11:22

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20240531_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='banner_overlay',
            field=models.BooleanField(default=False, verbose_name='Banner Overlay'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='pricingplantranslation',
            name='banner_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Banner Description'),
        ),
        migrations.AddField(
            model_name='pricingplantranslation',
            name='banner_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banner Title'),
        ),
        migrations.AddField(
            model_name='pricingplantranslation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Page Content'),
        ),
        migrations.AddField(
            model_name='pricingplantranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='pricingplantranslation',
            name='page_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='pricingplantranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
    ]
