# Generated by Django 3.2 on 2024-05-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_auto_20240531_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdoctorpageseo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='aboutpageseo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='jineartclinicpageseo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='jineartlabpageseo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Image'),
        ),
    ]
