# Generated by Django 3.2 on 2024-05-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_auto_20240531_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Service Item', 'verbose_name_plural': 'Service Items'},
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordering'),
        ),
    ]
