# Generated by Django 3.2 on 2024-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_priceserviceitem_priceserviceitemtranslation_pricespageseo_pricespageseotranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceserviceitem',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Price'),
        ),
    ]
