# Generated by Django 3.2 on 2024-06-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0024_alter_priceserviceitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howitworkspageseo',
            options={'verbose_name': 'Plan Your Journey Page SEO', 'verbose_name_plural': 'Plan Your Journey Page SEO'},
        ),
        migrations.AlterModelOptions(
            name='howitworkspageseotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Plan Your Journey Page SEO Translation'},
        ),
        migrations.AlterModelOptions(
            name='jineartclinicpageseo',
            options={'verbose_name': 'Why Us Page SEO', 'verbose_name_plural': 'Why Us Page SEO'},
        ),
        migrations.AlterModelOptions(
            name='jineartclinicpageseotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Why Us Page SEO Translation'},
        ),
        migrations.AlterModelOptions(
            name='jineartlabpageseo',
            options={'verbose_name': 'Success Rates Page SEO', 'verbose_name_plural': 'Success Rates Page SEO'},
        ),
        migrations.AlterModelOptions(
            name='jineartlabpageseotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Success Rates Page SEO Translation'},
        ),
        migrations.AlterField(
            model_name='priceserviceitemtranslation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
