# Generated by Django 3.2 on 2024-06-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_auto_20240601_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdoctorpageseotranslation',
            name='faq_description',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ Description'),
        ),
        migrations.AddField(
            model_name='aboutdoctorpageseotranslation',
            name='faq_subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutdoctorpageseotranslation',
            name='faq_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Title'),
        ),
        migrations.AddField(
            model_name='aboutpageseotranslation',
            name='faq_description',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ Description'),
        ),
        migrations.AddField(
            model_name='aboutpageseotranslation',
            name='faq_subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutpageseotranslation',
            name='faq_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Title'),
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='faq_description',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ Description'),
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='faq_subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Subtitle'),
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='faq_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Title'),
        ),
        migrations.AddField(
            model_name='howitworkspageseotranslation',
            name='faq_description',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ Description'),
        ),
        migrations.AddField(
            model_name='howitworkspageseotranslation',
            name='faq_subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Subtitle'),
        ),
        migrations.AddField(
            model_name='howitworkspageseotranslation',
            name='faq_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Title'),
        ),
        migrations.AddField(
            model_name='jineartclinicpageseotranslation',
            name='faq_description',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ Description'),
        ),
        migrations.AddField(
            model_name='jineartclinicpageseotranslation',
            name='faq_subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Subtitle'),
        ),
        migrations.AddField(
            model_name='jineartclinicpageseotranslation',
            name='faq_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Title'),
        ),
        migrations.AddField(
            model_name='jineartlabpageseotranslation',
            name='faq_description',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ Description'),
        ),
        migrations.AddField(
            model_name='jineartlabpageseotranslation',
            name='faq_subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Subtitle'),
        ),
        migrations.AddField(
            model_name='jineartlabpageseotranslation',
            name='faq_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Title'),
        ),
        migrations.AddField(
            model_name='serviceitemtranslation',
            name='faq_description',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ Description'),
        ),
        migrations.AddField(
            model_name='serviceitemtranslation',
            name='faq_subtitle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Subtitle'),
        ),
        migrations.AddField(
            model_name='serviceitemtranslation',
            name='faq_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Title'),
        ),
    ]
