# Generated by Django 3.2 on 2024-07-15 10:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_auto_20240602_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqtranslation',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='Answer'),
        ),
    ]
