# Generated by Django 3.2 on 2024-07-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_alter_faqtranslation_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='in_about_page',
            field=models.BooleanField(default=False, verbose_name='In About Page?'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='in_doctor_page',
            field=models.BooleanField(default=False, verbose_name='In Cengiz Sagiroglu Page?'),
        ),
    ]
