# Generated by Django 3.2 on 2024-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0029_auto_20240722_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerslide',
            name='redirect_link',
        ),
        migrations.AddField(
            model_name='bannerslidetranslation',
            name='redirect_link',
            field=models.CharField(blank=True, help_text="You can enter full url or relative path like '/about'", max_length=300, null=True, verbose_name='Redirect Link'),
        ),
    ]
