# Generated by Django 3.2 on 2024-08-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0030_auto_20240812_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyitemtranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
