from .common import *
from .home import *
from .about import *
from .services import *
from .journey import *
from .experience import *
from .blogs import *
from .contact import *
from .gdpr import *
from .comments import *
from .pricing import *
from .faqs import *
